name: git-auto-commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "15 * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3
  
jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use git-auto-commit-action
      id: "auto-commit-action"
      uses: ./

    - name: "no changes detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: "echo \"No changes detected\""

    - name: "changes detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: "echo \"Changes detected\""
