name: Release Drafter

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "15 * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
